baseurl: https://radhikabhargava1.netlify.app/
languageCode: en-us
title: Lithium Theme
theme: hugo-lithium-theme
googleAnalytics: ''
disqusShortname: ''
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
  - '404'
permalinks:
  page: /:title/
  post: /:year/:month/:day/:title/
menu:
  main:
    - name: Ongoing Projects
      url: /projects/
    - name: Publications and Conferences
      url: /publications/
    - name: Education & Teaching
      url: /education/
    
params:
  description: ''
  favicon: favicon.ico
  icon:
    url: favicon.ico
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
  mainSections: post
